# Generated by Django 4.2 on 2023-05-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelID', models.CharField(max_length=100)),
                ('channel_name', models.CharField(default='', max_length=100, null=True)),
                ('views', models.BigIntegerField(default=0, null=True)),
                ('hidden_sub', models.IntegerField(default=0, null=True)),
                ('subscribers', models.IntegerField(default=0, null=True)),
                ('videos', models.IntegerField(default=0, null=True)),
                ('revenue', models.FloatField(default=0, null=True)),
                ('channel_img', models.ImageField(default=0, null=True, upload_to='')),
                ('video_title', models.TextField(default='', max_length=1000, null=True)),
                ('video_category_id', models.TextField(default='', max_length=1000, null=True)),
                ('video_views', models.TextField(default='', max_length=1000, null=True)),
                ('video_likes', models.TextField(default='', max_length=1000, null=True)),
                ('video_comments', models.TextField(default='', max_length=1000, null=True)),
                ('video_date', models.TextField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
