# Generated by Django 4.1.7 on 2023-03-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelinfo',
            name='channel_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='hidden_sub',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='revenue',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='subscribers',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='videos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
