# Generated by Django 4.1.7 on 2023-03-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_channelinfo_channel_name_channelinfo_hidden_sub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelinfo',
            name='view',
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='views',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
