# Generated by Django 4.2 on 2023-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_analyticsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsinfo',
            name='channel_id',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
