# Generated by Django 4.2 on 2023-05-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_analyticsinfo_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsinfo',
            name='subscribersViewRatio',
            field=models.FloatField(default=0, null=True),
        ),
    ]
