# Generated by Django 4.1.7 on 2023-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_videolist_channelinfo_channel_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoList',
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='video_category_id',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='video_comments',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='video_date',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='video_likes',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='video_title',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='channelinfo',
            name='video_views',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
