# Generated by Django 4.2 on 2023-05-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_analyticsinfo_subscribersviewratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsinfo',
            old_name='subscribersViewRatio',
            new_name='subscribersViewsRatio',
        ),
    ]
