# Generated by Django 4.2 on 2023-05-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_subscribersviewratio_analyticsinfo_subscribersviewsratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsinfo',
            name='audienceWatchRatio',
        ),
        migrations.RemoveField(
            model_name='analyticsinfo',
            name='relativeRetentionPerformance',
        ),
    ]
