# Generated by Django 4.1.7 on 2023-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_videolist_channelinfo_video_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelinfo',
            name='channel_img',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
