# Generated by Django 4.1.7 on 2023-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_channelinfo_channel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelinfo',
            name='video_url',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
