# Generated by Django 4.1.7 on 2023-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_channelinfo_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularChannelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_category', models.CharField(default='', max_length=100)),
                ('channelID', models.CharField(default='', max_length=100)),
                ('channel_name', models.CharField(default='', max_length=100, null=True)),
                ('channel_views', models.BigIntegerField(default=0, null=True)),
                ('hidden_sub', models.IntegerField(default=0, null=True)),
                ('subscribers', models.IntegerField(default=0, null=True)),
                ('channel_thumbnail', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('channel_title', models.CharField(default='', max_length=100, null=True)),
                ('views', models.BigIntegerField(default=0, null=True)),
                ('video_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
