# Generated by Django 4.1.7 on 2023-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_popularchannelinfo_trendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelinfo',
            name='LoadDate',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popularchannelinfo',
            name='LoadDate',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trendlist',
            name='LoadDate',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
