# Generated by Django 4.1.7 on 2023-05-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_channelinfo_loaddate_popularchannelinfo_loaddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularchannelinfo',
            old_name='hidden_sub',
            new_name='ranking_subscribers',
        ),
        migrations.AddField(
            model_name='popularchannelinfo',
            name='ranking_viewcounters',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
