# Generated by Django 4.2 on 2023-05-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_channelinfo_loaddate_popularchannelinfo_loaddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0, null=True)),
                ('category_name', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trendlist',
            name='category_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
