# Generated by Django 4.2 on 2023-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_hidden_sub_popularchannelinfo_ranking_subscribers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('views', models.BigIntegerField(default=0, null=True)),
                ('comments', models.BigIntegerField(default=0, null=True)),
                ('likes', models.BigIntegerField(default=0, null=True)),
                ('dislikes', models.BigIntegerField(default=0, null=True)),
                ('shares', models.BigIntegerField(default=0, null=True)),
                ('subscribersGained', models.BigIntegerField(default=0, null=True)),
                ('subscribersLost', models.BigIntegerField(default=0, null=True)),
                ('estimatedMinutesWatched', models.BigIntegerField(default=0, null=True)),
                ('subscribersViewsRatio', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
