# Generated by Django 4.1.7 on 2023-05-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_analyticsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendlist',
            name='category_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
