# Generated by Django 4.1.7 on 2023-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_trendlist_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0, null=True)),
                ('category_name', models.CharField(default='', max_length=100, null=True)),
                ('ranking_subscribers', models.IntegerField(default=0, null=True)),
                ('ranking_viewcounters', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
