# Generated by Django 4.1.7 on 2023-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ranking_subscribers',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
