# Generated by Django 4.1.7 on 2023-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_category_ranking_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ranking_subscribers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
